// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalcTempsPasseController from "./calc_temps_passe_controller"
application.register("calc-temps-passe", CalcTempsPasseController)

import CommandeLigneController from "./commande_ligne_controller"
application.register("commande-ligne", CommandeLigneController)

import ConversationController from "./conversation_controller"
application.register("conversation", ConversationController)

import CotationLigneController from "./cotation_ligne_controller"
application.register("cotation-ligne", CotationLigneController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import DynamicSelectController from "./dynamic_select_controller"
application.register("dynamic-select", DynamicSelectController)

import FactureLigneController from "./facture_ligne_controller"
application.register("facture-ligne", FactureLigneController)

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import MeteoInterventionController from "./meteo_intervention_controller"
application.register("meteo-intervention", MeteoInterventionController)

import NewsletterController from "./newsletter_controller"
application.register("newsletter", NewsletterController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PasswordStrengthController from "./password_strength_controller"
application.register("password-strength", PasswordStrengthController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import PlacesController from "./places_controller"
application.register("places", PlacesController)

import RailsNestedFormController from "./rails_nested_form_controller"
application.register("rails-nested-form", RailsNestedFormController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)

import TextareaAutogrowController from "./textarea_autogrow_controller"
application.register("textarea-autogrow", TextareaAutogrowController)

import ToggleRoleInfoController from "./toggle_role_info_controller"
application.register("toggle-role-info", ToggleRoleInfoController)

import ToggleVisibilityController from "./toggle_visibility_controller"
application.register("toggle-visibility", ToggleVisibilityController)

import VerificationDisponibilitesController from "./verification_disponibilites_controller"
application.register("verification-disponibilites", VerificationDisponibilitesController)
